### PR TITLE
Threading API and other enhancements

### PR DESCRIPTION
**Pull request by rth**
This PR adds the following functionality,
  - exposes the threading API for `FreeDiscovery/jwzthreading`. A threading example can be found [in the docs](https://freediscovery.github.io/doc/dev/examples/email_threading_example.html) (after this PR is merged).
  - fixes issue #34 
  - adds links from the documentation (Python API) to github code.

### CODE REVIEW

**Comment by DenisFLASH** [comment]
@rth i have a problem with running unit tests. Here is the [screenshot](http://www.hostingpics.net/viewer.php?id=99909120161214errorintestparsers.png)

In order to build the project, i had to add Git in Windows PATH variable, is otherwise it was not possible to install a newly added `git+https://github.com/FreeDiscovery/jwzthreading.git` dependency in requirements file, as running BAT file uses Windows shell which does not have Git command.

I don't think it can cause a problem since this repo is now installed and `from jwzthreading import Message` works well.

**Comment by DenisFLASH** [comment]
the error occures in `tests/test_parsers.py` which calls `list_datasets` from `base.py`. Then, in `list_datasets` the `pars` dictionary doesn't have "type" key. Hve you already got this type of error during the refactoring after adding email threading?

**Comment by rth** [comment]
@DenisFLASH OK, makes sens. I changed slightly the format of files saved to disk in the last PR. These issues should go away if you remove your `ediscovery_cache` folder (on Linux it's in `/tmp/ediscovery_cache` by default), as now you probably have a mix of old style and new style files there...

**Comment by DenisFLASH** [comment]
indeed, everything is alright now, thanks!
Btw, this `ediscovery_cache` folder keeps growing till every time i launch tests, and thus i delete it manually from time to time. Don you need to do the same?

**Pull request merged**
